BEGIN;

DROP TABLE IF EXISTS topthree CASCADE;
DROP TABLE IF EXISTS organisations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS charities CASCADE;
DROP TABLE IF EXISTS petitions CASCADE;
DROP TABLE IF EXISTS followers CASCADE;

COMMIT;